// src/lib/PalmsListingCard.svelte
<!--
  PalmsListingCard — Featured listing widget for Palms Place #822
  MLS# 2782527 · $437,777 · Active

  TO REMOVE when listing sells:
    1. Delete this file
    2. Remove import + <PalmsListingCard /> from any page that imports it
-->
<div class="palms-card">
  <div class="gold-bar"></div>

  <div class="badge-row">
    <span class="featured-badge">✦ Featured Listing</span>
    <span class="agent-label">Dr. Jan Duffy · BHHS Nevada Properties</span>
  </div>

  <div class="price-block">
    <div class="price">$437,777</div>
    <div class="address">4381 W Flamingo Rd #822 · Palms Place</div>
    <div class="sub-address">Las Vegas, NV 89103 · MLS# 2782527</div>
  </div>

  <div class="badges">
    {#each ['🏨 STR Permitted', '💡 HOA Covers All Utilities', '🏢 8th Floor Corner', '📐 1,220 SF', '🌟 Strip Views'] as badge}
      <span class="badge">{badge}</span>
    {/each}
  </div>

  <div class="cta-row">
    <a href="tel:702-222-1964" class="btn-cta">📞 Call/Text 702-222-1964</a>
    <a
      href="https://drjanduffy.com/property/4381-w-flamingo-rd-822-las-vegas-nv-89103"
      target="_blank"
      rel="noopener noreferrer"
      class="link-details"
    >View Full Details →</a>
  </div>
</div>

<style>
  .palms-card {
    background: linear-gradient(135deg, #0A2440 0%, #0d2d52 100%);
    border: 1px solid #C9A84C;
    border-radius: 12px;
    padding: 28px 32px;
    margin: 32px 0;
    color: #fff;
    position: relative;
    overflow: hidden;
    box-shadow: 0 8px 32px rgba(0,0,0,0.3);
    font-family: Inter, system-ui, sans-serif;
  }
  .gold-bar {
    position: absolute;
    top: 0; left: 0; right: 0;
    height: 3px;
    background: linear-gradient(90deg, #C9A84C, #F0D080, #C9A84C);
  }
  .badge-row {
    display: flex;
    align-items: center;
    gap: 8px;
    margin-bottom: 12px;
    flex-wrap: wrap;
  }
  .featured-badge {
    background: #C9A84C;
    color: #0A2440;
    font-size: 11px;
    font-weight: 700;
    letter-spacing: 0.08em;
    text-transform: uppercase;
    padding: 3px 10px;
    border-radius: 20px;
  }
  .agent-label {
    font-size: 12px;
    color: #C9A84C;
    font-weight: 600;
  }
  .price-block {
    margin-bottom: 16px;
  }
  .price {
    font-size: 32px;
    font-weight: 800;
    color: #F0D080;
    letter-spacing: -0.5px;
    line-height: 1;
    margin-bottom: 6px;
  }
  .address {
    font-size: 16px;
    font-weight: 600;
    color: #e8edf2;
  }
  .sub-address {
    font-size: 13px;
    color: #94a3b8;
    margin-top: 2px;
  }
  .badges {
    display: flex;
    flex-wrap: wrap;
    gap: 8px;
    margin-bottom: 20px;
  }
  .badge {
    background: rgba(201,168,76,0.15);
    border: 1px solid rgba(201,168,76,0.4);
    color: #F0D080;
    font-size: 12px;
    font-weight: 600;
    padding: 4px 12px;
    border-radius: 20px;
    white-space: nowrap;
  }
  .cta-row {
    display: flex;
    flex-wrap: wrap;
    gap: 12px;
    align-items: center;
  }
  .btn-cta {
    background: #C9A84C;
    color: #0A2440;
    font-weight: 700;
    font-size: 14px;
    padding: 10px 22px;
    border-radius: 8px;
    text-decoration: none;
    display: inline-block;
    letter-spacing: 0.02em;
  }
  .link-details {
    color: #C9A84C;
    font-weight: 600;
    font-size: 13px;
    text-decoration: underline;
  }
</style>

// app/components/PalmsListingCard.tsx
/**
 * PalmsListingCard — Featured listing widget for Palms Place #822
 * MLS# 2782527 · $437,777 · Active
 *
 * TO REMOVE when listing sells:
 *   1. Delete this file
 *   2. Remove import + <PalmsListingCard /> from app/condos/palms-place/page.tsx
 */

export default function PalmsListingCard() {
  return (
    <div
      style={{
        background: 'linear-gradient(135deg, #0A2440 0%, #0d2d52 100%)',
        border: '1px solid #C9A84C',
        borderRadius: '12px',
        padding: '28px 32px',
        margin: '32px 0',
        fontFamily: 'Inter, system-ui, sans-serif',
        color: '#fff',
        position: 'relative',
        overflow: 'hidden',
        boxShadow: '0 8px 32px rgba(0,0,0,0.3)',
      }}
    >
      {/* Gold accent line */}
      <div
        style={{
          position: 'absolute',
          top: 0,
          left: 0,
          right: 0,
          height: '3px',
          background: 'linear-gradient(90deg, #C9A84C, #F0D080, #C9A84C)',
        }}
      />

      {/* Featured badge */}
      <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '12px', flexWrap: 'wrap' as const }}>
        <span
          style={{
            background: '#C9A84C',
            color: '#0A2440',
            fontSize: '11px',
            fontWeight: '700',
            letterSpacing: '0.08em',
            textTransform: 'uppercase' as const,
            padding: '3px 10px',
            borderRadius: '20px',
          }}
        >
          ✦ Featured Listing — Active Now
        </span>
        <span style={{ fontSize: '12px', color: '#C9A84C', fontWeight: '600' }}>
          Dr. Jan Duffy · BHHS Nevada Properties
        </span>
      </div>

      {/* Price + address */}
      <div style={{ marginBottom: '16px' }}>
        <div
          style={{
            fontSize: '32px',
            fontWeight: '800',
            color: '#F0D080',
            letterSpacing: '-0.5px',
            lineHeight: 1,
            marginBottom: '6px',
          }}
        >
          $437,777
        </div>
        <div style={{ fontSize: '16px', fontWeight: '600', color: '#e8edf2' }}>
          4381 W Flamingo Rd #822 · Palms Place
        </div>
        <div style={{ fontSize: '13px', color: '#94a3b8', marginTop: '2px' }}>
          Las Vegas, NV 89103 · MLS# 2782527
        </div>
      </div>

      {/* Feature badges */}
      <div style={{ display: 'flex', flexWrap: 'wrap' as const, gap: '8px', marginBottom: '20px' }}>
        {[
          '🏨 STR Permitted',
          '💡 HOA Covers All Utilities',
          '🏢 8th Floor Corner',
          '📐 1,220 SF',
          '🌟 Strip Views',
        ].map((badge) => (
          <span
            key={badge}
            style={{
              background: 'rgba(201,168,76,0.15)',
              border: '1px solid rgba(201,168,76,0.4)',
              color: '#F0D080',
              fontSize: '12px',
              fontWeight: '600',
              padding: '4px 12px',
              borderRadius: '20px',
              whiteSpace: 'nowrap' as const,
            }}
          >
            {badge}
          </span>
        ))}
      </div>

      {/* CTA row */}
      <div style={{ display: 'flex', flexWrap: 'wrap' as const, gap: '12px', alignItems: 'center' }}>
        <a
          href="tel:702-222-1964"
          style={{
            background: '#C9A84C',
            color: '#0A2440',
            fontWeight: '700',
            fontSize: '14px',
            padding: '10px 22px',
            borderRadius: '8px',
            textDecoration: 'none',
            display: 'inline-block',
            letterSpacing: '0.02em',
          }}
        >
          📞 Call/Text 702-222-1964
        </a>
        <a
          href="https://drjanduffy.com/property/4381-w-flamingo-rd-822-las-vegas-nv-89103"
          target="_blank"
          rel="noopener noreferrer"
          style={{
            color: '#C9A84C',
            fontWeight: '600',
            fontSize: '13px',
            textDecoration: 'underline',
          }}
        >
          View Full Details →
        </a>
      </div>
    </div>
  )
}
