// app/components/header.tsx
'use client'

import Link from 'next/link'
import { usePathname } from 'next/navigation'
import { Phone, Menu, X, ChevronDown } from 'lucide-react'
import { useState } from 'react'

export default function Header() {
  const pathname = usePathname()
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false)
  const [servicesOpen, setServicesOpen] = useState(false)
  const [condosOpen, setCondosOpen] = useState(false)

  const mainNavItems = [
    { href: '/', label: 'Home' },
    { href: '/sell-house-fast-las-vegas', label: 'Sell Your Home' },
    { href: '/home-wont-sell-las-vegas', label: 'Home will not Sell?' },
    { href: '/summerlin-real-estate-agent', label: 'Summerlin Agent' },
    { href: '/neighborhoods', label: 'Neighborhoods' },
    { href: '/blog', label: 'Blog' },
    { href: '/about', label: 'About' },
    { href: '/contact', label: 'Contact' },
  ]

  const servicesItems = [
    { href: '/services', label: 'Services' },
    { href: '/process', label: 'Selling Process' },
    { href: '/marketing-strategy', label: 'Marketing Strategy' },
    { href: '/why-choose-me', label: 'Why Choose Me' },
    { href: '/comparison', label: 'Agent Comparison' },
  ]

  const condosItems = [
    { href: '/condos', label: 'All Condos' },
    { href: '/condos/strip', label: 'Strip Condos' },
    { href: '/condos/luxury', label: 'Luxury Condos' },
    { href: '/condos/high-rise', label: 'High-Rise Condos' },
    { href: '/condos/mid-rise', label: 'Mid-Rise Condos' },
    { href: '/condos/summerlin', label: 'Summerlin Condos' },
    { href: '/condos/henderson', label: 'Henderson Condos' },
  ]

  const resourcesItems = [
    { href: '/resources', label: 'Free Resources' },
    { href: '/answers', label: 'Seller Answers' },
    { href: '/tools/cost-calculator', label: 'Cost Calculator' },
    { href: '/tools/blame-analyzer', label: 'Blame Analyzer' },
    { href: '/why-expire', label: 'Why homes fail to sell' },
    { href: '/testimonials', label: 'Testimonials' },
  ]

  const isActive = (href: string) => {
    if (href === '/') {
      return pathname === '/'
    }
    return pathname.startsWith(href)
  }

  return (
    <>
      {/* Top Stats Bar */}
      <div className="bg-primary text-primary-foreground text-sm py-2">
        <div className="container mx-auto px-4">
          <div className="flex items-center justify-center gap-4 flex-wrap">
            <span className="font-bold">🔥 7 homes that DID NOT sell - now sold</span>
            <span className="hidden md:inline">|</span>
            <span className="hidden md:inline">19 Day Average</span>
            <span className="hidden md:inline">|</span>
            <span className="hidden md:inline">98.7% of Asking Price</span>
          </div>
        </div>
      </div>

      {/* Main Header */}
      <header className="bg-white border-b-2 border-gray-200 sticky top-0 z-50 shadow-sm">
        <div className="container mx-auto px-4">
          <div className="flex items-center justify-between h-20">
            {/* Logo/Brand */}
            <Link href="/" className="flex items-center gap-3 flex-shrink-0">
              <div className="flex flex-col">
                <span className="text-2xl font-black text-gray-900 leading-tight">
                  Dr. Jan Duffy
                </span>
                <span className="text-xs text-gray-700 font-semibold">
                  Failed Listing Specialist
                </span>
              </div>
            </Link>

            {/* Desktop Navigation */}
            <nav className="hidden lg:flex items-center gap-1 flex-1 justify-center">
              {mainNavItems.map((item) => (
                <Link
                  key={item.href}
                  href={item.href}
                  className={`px-4 py-2 rounded-lg font-semibold transition-colors ${
                    isActive(item.href)
                      ? 'text-primary bg-primary/10'
                      : 'text-gray-700 hover:text-primary hover:bg-gray-100'
                  }`}
                >
                  {item.label}
                </Link>
              ))}

              {/* Services Dropdown */}
              <div
                className="relative group"
                onMouseEnter={() => setServicesOpen(true)}
                onMouseLeave={() => setServicesOpen(false)}
              >
                <button
                  className={`px-4 py-2 rounded-lg font-semibold transition-colors flex items-center gap-1 ${
                    pathname.startsWith('/services') || pathname.startsWith('/process') || pathname.startsWith('/marketing-strategy') || pathname.startsWith('/why-choose-me') || pathname.startsWith('/comparison')
                      ? 'text-primary bg-primary/10'
                      : 'text-gray-700 hover:text-primary hover:bg-gray-100'
                  }`}
                >
                  Services
                  <ChevronDown className="w-4 h-4" />
                </button>
                {servicesOpen && (
                  <div className="absolute top-full left-0 mt-1 w-56 bg-white border-2 border-gray-200 rounded-lg shadow-xl py-2">
                    {servicesItems.map((item) => (
                      <Link
                        key={item.href}
                        href={item.href}
                        className={`block px-4 py-2 hover:bg-primary/10 hover:text-primary transition-colors ${
                          isActive(item.href) ? 'text-primary font-semibold' : 'text-gray-700'
                        }`}
                      >
                        {item.label}
                      </Link>
                    ))}
                  </div>
                )}
              </div>

              {/* Condos Dropdown */}
              <div
                className="relative group"
                onMouseEnter={() => setCondosOpen(true)}
                onMouseLeave={() => setCondosOpen(false)}
              >
                <button
                  className={`px-4 py-2 rounded-lg font-semibold transition-colors flex items-center gap-1 ${
                    pathname.startsWith('/condos')
                      ? 'text-primary bg-primary/10'
                      : 'text-gray-700 hover:text-primary hover:bg-gray-100'
                  }`}
                >
                  Condos
                  <ChevronDown className="w-4 h-4" />
                </button>
                {condosOpen && (
                  <div className="absolute top-full left-0 mt-1 w-56 bg-white border-2 border-gray-200 rounded-lg shadow-xl py-2 max-h-96 overflow-y-auto">
                    {condosItems.map((item) => (
                      <Link
                        key={item.href}
                        href={item.href}
                        className={`block px-4 py-2 hover:bg-primary/10 hover:text-primary transition-colors ${
                          isActive(item.href) ? 'text-primary font-semibold' : 'text-gray-700'
                        }`}
                      >
                        {item.label}
                      </Link>
                    ))}
                  </div>
                )}
              </div>

              {/* Resources Link */}
              <Link
                href="/resources"
                className={`px-4 py-2 rounded-lg font-semibold transition-colors ${
                  pathname.startsWith('/resources') || pathname.startsWith('/tools') || pathname.startsWith('/why-expire') || pathname.startsWith('/testimonials')
                    ? 'text-primary bg-primary/10'
                    : 'text-gray-700 hover:text-primary hover:bg-gray-100'
                }`}
              >
                Resources
              </Link>
            </nav>

            {/* CTA Button */}
            <div className="flex items-center gap-3 flex-shrink-0">
              <a
                href="tel:7025001064"
                className="hidden sm:flex items-center gap-2 bg-[var(--color-cta)] text-[var(--color-cta-foreground)] px-6 py-3 rounded-lg font-bold hover:bg-[var(--color-cta-hover)] transition-colors shadow-md"
              >
                <Phone className="w-5 h-5" />
                <span>(702) 500-1064</span>
              </a>
              <a
                href="tel:7025001064"
                className="sm:hidden flex items-center justify-center w-12 h-12 bg-[var(--color-cta)] text-[var(--color-cta-foreground)] rounded-lg font-bold hover:bg-[var(--color-cta-hover)] transition-colors shadow-md"
              >
                <Phone className="w-5 h-5" />
              </a>

              {/* Mobile Menu Button */}
              <button
                onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
                className="lg:hidden p-2 text-gray-700 hover:text-primary transition-colors"
                aria-label="Toggle menu"
              >
                {mobileMenuOpen ? <X className="w-6 h-6" /> : <Menu className="w-6 h-6" />}
              </button>
            </div>
          </div>
        </div>

        {/* Mobile Menu */}
        {mobileMenuOpen && (
          <div className="lg:hidden border-t border-gray-200 bg-white">
            <div className="container mx-auto px-4 py-4 space-y-1">
              {mainNavItems.map((item) => (
                <Link
                  key={item.href}
                  href={item.href}
                  onClick={() => setMobileMenuOpen(false)}
                  className={`block px-4 py-3 rounded-lg font-semibold transition-colors ${
                    isActive(item.href)
                      ? 'text-primary bg-primary/10'
                      : 'text-gray-700 hover:text-primary hover:bg-gray-100'
                  }`}
                >
                  {item.label}
                </Link>
              ))}

              {/* Mobile Services Section */}
              <div className="pt-2">
                <div className="px-4 py-2 text-sm font-bold text-gray-700 uppercase">Services</div>
                {servicesItems.map((item) => (
                  <Link
                    key={item.href}
                    href={item.href}
                    onClick={() => setMobileMenuOpen(false)}
                    className={`block px-4 py-2 rounded-lg transition-colors ${
                      isActive(item.href)
                        ? 'text-primary bg-primary/10 font-semibold'
                        : 'text-gray-700 hover:text-primary hover:bg-gray-100'
                    }`}
                  >
                    {item.label}
                  </Link>
                ))}
              </div>

              {/* Mobile Condos Section */}
              <div className="pt-2">
                <div className="px-4 py-2 text-sm font-bold text-gray-700 uppercase">Condos</div>
                {condosItems.map((item) => (
                  <Link
                    key={item.href}
                    href={item.href}
                    onClick={() => setMobileMenuOpen(false)}
                    className={`block px-4 py-2 rounded-lg transition-colors ${
                      isActive(item.href)
                        ? 'text-primary bg-primary/10 font-semibold'
                        : 'text-gray-700 hover:text-primary hover:bg-gray-100'
                    }`}
                  >
                    {item.label}
                  </Link>
                ))}
              </div>

              {/* Mobile Resources Section */}
              <div className="pt-2">
                <div className="px-4 py-2 text-sm font-bold text-gray-700 uppercase">Resources</div>
                {resourcesItems.map((item) => (
                  <Link
                    key={item.href}
                    href={item.href}
                    onClick={() => setMobileMenuOpen(false)}
                    className={`block px-4 py-2 rounded-lg transition-colors ${
                      isActive(item.href)
                        ? 'text-primary bg-primary/10 font-semibold'
                        : 'text-gray-700 hover:text-primary hover:bg-gray-100'
                    }`}
                  >
                    {item.label}
                  </Link>
                ))}
              </div>

              {/* Mobile CTA */}
              <div className="pt-4 border-t border-gray-200">
                <a
                  href="tel:7025001064"
                  onClick={() => setMobileMenuOpen(false)}
                  className="flex items-center justify-center gap-2 bg-[var(--color-cta)] text-[var(--color-cta-foreground)] px-6 py-3 rounded-lg font-bold hover:bg-[var(--color-cta-hover)] transition-colors shadow-md"
                >
                  <Phone className="w-5 h-5" />
                  <span>Call (702) 500-1064</span>
                </a>
              </div>
            </div>
          </div>
        )}
      </header>
    </>
  )
}

// src/lib/components/Header.svelte
<script lang="ts">
  import { page } from '$app/stores';
  import { Menu, X, Phone, ChevronDown } from 'lucide-svelte';
  
  let mobileMenuOpen = false;
  let dropdownOpen = '';
  
  const phoneNumber = '(702) 222-1964';
  
  const navigation = [
    {
      name: 'Buy',
      href: '/buy',
      dropdown: [
        { name: 'Search Homes', href: '/properties' },
        { name: 'New Listings', href: '/properties?sort=newest' },
        { name: 'Open Houses', href: '/open-houses' },
        { name: 'Buyer Resources', href: '/buyers-guide' }
      ]
    },
    {
      name: 'Sell',
      href: '/sell',
      dropdown: [
        { name: 'Home Valuation', href: '/home-valuation' },
        { name: 'Marketing Plan', href: '/marketing' },
        { name: 'Seller Resources', href: '/sellers-guide' }
      ]
    },
    {
      name: 'Communities',
      href: '/communities',
      dropdown: [
        { name: 'West Summerlin', href: '/communities/west-summerlin' },
        { name: 'The Ridges', href: '/communities/the-ridges' },
        { name: 'Red Rock Country Club', href: '/communities/red-rock' },
        { name: 'Anthem Country Club', href: '/communities/anthem' },
        { name: 'MacDonald Highlands', href: '/communities/macdonald' },
        { name: 'Seven Hills', href: '/communities/seven-hills' }
      ]
    },
    {
      name: 'About Dr. Duffy',
      href: '/about'
    },
    {
      name: 'Blog',
      href: '/blog'
    },
    {
      name: 'Contact',
      href: '/contact'
    }
  ];
  
  function toggleDropdown(name: string) {
    dropdownOpen = dropdownOpen === name ? '' : name;
  }
  
  function closeDropdowns() {
    dropdownOpen = '';
  }
  
  function closeMobileMenu() {
    mobileMenuOpen = false;
  }
</script>

<header class="sticky top-0 z-50 bg-white shadow-lg">
  <!-- Top contact bar -->
  <div class="bg-primary-600 text-white py-2">
    <div class="container mx-auto px-4">
      <div class="flex justify-between items-center text-sm">
        <div class="flex items-center gap-4">
          <a href="tel:{phoneNumber}" class="flex items-center gap-1 hover:text-primary-100 transition-colors">
            <Phone size={14} />
            Call Dr. Duffy: {phoneNumber}
          </a>
          <span class="hidden md:inline">|</span>
          <a href="mailto:drduffy@bhhsnv.com" class="hidden md:flex items-center gap-1 hover:text-primary-100 transition-colors">
            drduffy@bhhsnv.com
          </a>
        </div>
        <div class="hidden lg:flex items-center gap-1 text-primary-100">
          <span>Serving Las Vegas & Surrounding Areas</span>
        </div>
      </div>
    </div>
  </div>

  <!-- Main navigation -->
  <nav class="container mx-auto px-4">
    <div class="flex justify-between items-center py-4">
      <!-- Logo/Branding -->
      <a href="/" class="flex items-center group">
        <div class="text-2xl lg:text-3xl font-display font-bold text-primary-600 group-hover:text-primary-700 transition-colors">
          Dr. Jan Duffy
        </div>
        <div class="ml-2 text-sm lg:text-base text-neutral-600 font-medium">
          REALTOR<sup>®</sup>
        </div>
      </a>

      <!-- Desktop Navigation -->
      <div class="hidden lg:flex items-center gap-8">
        {#each navigation as item}
          <div class="relative" on:mouseleave={closeDropdowns}>
            <button
              on:click={() => toggleDropdown(item.name)}
              class="flex items-center gap-1 text-neutral-700 hover:text-primary-600 font-medium transition-colors py-2"
              class:text-primary-600={$page.url.pathname.startsWith(item.href)}
            >
              {item.name}
              {#if item.dropdown}
                <ChevronDown size={16} class="transition-transform" class:rotate-180={dropdownOpen === item.name} />
              {/if}
            </button>
            
            {#if item.dropdown && dropdownOpen === item.name}
              <div class="absolute top-full left-0 mt-2 w-64 bg-white rounded-lg shadow-xl border border-neutral-200 py-2">
                {#each item.dropdown as subItem}
                  <a 
                    href={subItem.href}
                    class="block px-4 py-3 text-sm text-neutral-700 hover:bg-primary-50 hover:text-primary-600 transition-colors"
                    on:click={closeDropdowns}
                  >
                    {subItem.name}
                  </a>
                {/each}
              </div>
            {/if}
          </div>
        {/each}
        
        <!-- CTA Button -->
        <a href="/contact" class="btn-primary">
          Get Started
        </a>
      </div>

      <!-- Mobile menu button -->
      <button 
        class="lg:hidden p-2 text-neutral-700 hover:text-primary-600 transition-colors"
        on:click={() => mobileMenuOpen = !mobileMenuOpen}
        aria-label="Toggle mobile menu"
      >
        {#if mobileMenuOpen}
          <X size={24} />
        {:else}
          <Menu size={24} />
        {/if}
      </button>
    </div>

    <!-- Mobile Navigation -->
    {#if mobileMenuOpen}
      <div class="lg:hidden border-t bg-white">
        <div class="py-4 space-y-2">
          {#each navigation as item}
            <div>
              <a 
                href={item.href}
                class="block py-3 px-4 text-neutral-700 hover:text-primary-600 hover:bg-primary-50 font-medium transition-colors"
                on:click={closeMobileMenu}
              >
                {item.name}
              </a>
              
              {#if item.dropdown}
                <div class="ml-4 space-y-1">
                  {#each item.dropdown as subItem}
                    <a 
                      href={subItem.href}
                      class="block py-2 px-4 text-sm text-neutral-600 hover:text-primary-600 hover:bg-primary-50 transition-colors"
                      on:click={closeMobileMenu}
                    >
                      {subItem.name}
                    </a>
                  {/each}
                </div>
              {/if}
            </div>
          {/each}
          
          <!-- Mobile CTA -->
          <div class="pt-4 border-t">
            <a href="/contact" class="btn-primary w-full text-center block" on:click={closeMobileMenu}>
              Get Started
            </a>
          </div>
          
          <!-- Mobile Contact Info -->
          <div class="pt-4 border-t">
            <a href="tel:{phoneNumber}" class="flex items-center gap-2 py-2 px-4 text-primary-600 font-medium">
              <Phone size={16} />
              Call Dr. Duffy: {phoneNumber}
            </a>
            <a href="mailto:drduffy@bhhsnv.com" class="block py-2 px-4 text-neutral-600 text-sm">
              drduffy@bhhsnv.com
            </a>
          </div>
        </div>
      </div>
    {/if}
  </nav>
</header>

<style>
  .btn-primary {
    @apply bg-primary-600 text-white px-6 py-3 rounded-lg font-medium 
           hover:bg-primary-700 transition-colors duration-200 
           focus:outline-none focus:ring-2 focus:ring-primary-500 focus:ring-offset-2;
  }
</style>
